// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hrueswntudteckamscdp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhydWVzd250dWR0ZWNrYW1zY2RwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODMzMzA0MzUsImV4cCI6MjA5ODkwNjQzNX0.HE6Gk-SVNy-0N-muknuH1pKXPvx-0jtnuX0I3ZW665s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});